export const AppImages = {
  onboard1: require("../assets/Icons/onboard1.png"),
  onboard2: require("../assets/Icons/onboard2.png"),
  onboard3: require("../assets/Icons/onboard3.png"),
  back: require("../assets/Icons/back.png"),
  congratulationsView: require("../assets/Icons/congratulationsView.png"),
  menu: require("../assets/Icons/menu.png"),
  backwl: require("../assets/Icons/backwl.png"),
  home: require("../assets/Icons/home.png"),
  homefocused: require("../assets/Icons/homefocused.png"),
  bookingfocused: require("../assets/Icons/bookingfocused.png"),
  storefocused: require("../assets/Icons/storefocused.png"),
  shop: require("../assets/Icons/shop.png"),
  booking: require("../assets/Icons/booking.png"),
  chat: require("../assets/Icons/chat.png"),
  chatfocused: require("../assets/Icons/chatfocused.png"),
  star: require("../assets/Icons/star.png"),
  remove: require("../assets/Icons/remove.png"),
  plus: require("../assets/Icons/plus.png"),
  dropdown: require("../assets/Icons/dropdown.png"),
  plusIcon: require("../assets/Icons/plusIcon.png"),
  card: require("../assets/Icons/card.png"),
  cash: require("../assets/Icons/cash.png"),
  check: require("../assets/Icons/check.png"),
  whiteback: require("../assets/Icons/whiteback.png"),
  address: require("../assets/Icons/address.png"),
  payment: require("../assets/Icons/payment.png"),
  profile: require("../assets/Icons/Profile.png"),
  forwardArrow: require("../assets/Icons/forwardArrow.png"),
  logout: require("../assets/Icons/logout.png"),
  send: require("../assets/Icons/send.png"),
  store: require("../assets/Icons/store.png"),
  search: require("../assets/Icons/search.png"),
  support: require("../assets/Icons/support.png"),
  triangle: require("../assets/Icons/triangle.png"),
  cross: require("../assets/Icons/cross.png"),

  jobtype: require("../assets/Icons/jobtype.png"),
  material: require("../assets/Icons/material.png"),
  paymentMehod: require("../assets/Icons/paymentmethod.png"),
  persons: require("../assets/Icons/persons.png"),
  price: require("../assets/Icons/price.png"),

  logo: require("../assets/Icons/logo.jpeg"),


};
